gateways:
  postgres:
    connection:
      type: postgres
      host: postgres.postgres
      port: 5432
      user: postgres
      password: 44569491a9d43226b06f
      database: postgres

  mysql:
    connection:
      type: mysql
      host: 10.0.40.105
      port: 3306
      user: read_only
      password: 4NjneaNJLNewew

default_gateway: postgres

model_defaults:
  dialect: postgres
  start: 2025-01-14
